### ISSUE TITLE
php7.1.2 error

### ISSUE THREAD

**Issue by robbinhan** [kitech/php-go#24]
PHP Warning:  PHP Startup: Unable to load dynamic library './hello.so' - dlopen(./hello.so, 9): Symbol not found: _zval_used_for_init
  Referenced from: ./hello.so
  Expected in: flat namespace
 in ./hello.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library './hello.so' - dlopen(./hello.so, 9): Symbol not found: _zval_used_for_init
  Referenced from: ./hello.so
  Expected in: flat namespace
 in ./hello.so in Unknown on line 0
PHP Fatal error:  Uncaught Error: Call to undefined function foo_hello() in /Users/robbin/go/src/github.com/kitech/php-go/examples/hello.php:5
Stack trace:
#0 /Users/robbin/go/src/github.com/kitech/php-go/examples/hello.php(58): test_funcs()
#1 {main}
  thrown in /Users/robbin/go/src/github.com/kitech/php-go/examples/hello.php on line 5

Fatal error: Uncaught Error: Call to undefined function foo_hello() in /Users/robbin/go/src/github.com/kitech/php-go/examples/hello.php:5
Stack trace:
#0 /Users/robbin/go/src/github.com/kitech/php-go/examples/hello.php(58): test_funcs()
#1 {main}
  thrown in /Users/robbin/go/src/github.com/kitech/php-go/examples/hello.php on line 5

**Comment by mweibel** [comment]
make sure to build using the correct php settings. you can point the `PHPCFG` env variable while building to the correct location. E.g. in my case: `PHPCFG=/usr/local/php7/bin/php-config make`

Otherwise it will use by default `/usr/bin/php-config` which in OSX's case is php5 and then you probably ran it with the php 7 version. 
Also the `make clean` doesn't clean up in the correct place if you use OSX.

**Comment by kitech** [comment]
merged master, give a try for free.
